// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

// Injectors from wire.go:

func NewApp() (*App, error) {
	appContext, err := provideAppContext()
	if err != nil {
		return nil, err
	}
	recordStore, err := provideRecordStore(appContext)
	if err != nil {
		return nil, err
	}
	v := provideSubCmds(appContext, recordStore)
	command := provideRootCmd(appContext, v)
	app := &App{
		Cmd: command,
	}
	return app, nil
}
