// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

// Injectors from wire.go:

func NewApp() (*App, error) {
	appContext := provideAppContext()
	v := provideSubCmds(appContext)
	command := provideRootCmd(appContext, v)
	app := &App{
		Cmd: command,
	}
	return app, nil
}
