version: '3.5'
services:
  db:
    image: postgres:latest
    container_name: gitcrow-db
    volumes:
      - gitcrow-db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - '5432:5432'

volumes:
  gitcrow-db:
