output = "infra/record"
pkgname = "record"

[psql]
    dbname = "gitcrow"
#    shema = "gitcrow"
    host = "localhost"
    port = 5432
    user = "taxio"
    pass = "hogehoge"
    sslmode = "disable"
    blacklist = ["schema_migrations"]
