// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package record

var TableNames = struct {
	Cached string
	Users  string
}{
	Cached: "cached",
	Users:  "users",
}
