// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gitcrow.proto

package api_pb // import "github.com/taxio/gitcrow/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CloneRepositoriesRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	SaveDir              string   `protobuf:"bytes,3,opt,name=save_dir,json=saveDir,proto3" json:"save_dir,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo                 string   `protobuf:"bytes,5,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloneRepositoriesRequest) Reset()         { *m = CloneRepositoriesRequest{} }
func (m *CloneRepositoriesRequest) String() string { return proto.CompactTextString(m) }
func (*CloneRepositoriesRequest) ProtoMessage()    {}
func (*CloneRepositoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gitcrow_7ef2d37406cf996b, []int{0}
}
func (m *CloneRepositoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneRepositoriesRequest.Unmarshal(m, b)
}
func (m *CloneRepositoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneRepositoriesRequest.Marshal(b, m, deterministic)
}
func (dst *CloneRepositoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneRepositoriesRequest.Merge(dst, src)
}
func (m *CloneRepositoriesRequest) XXX_Size() int {
	return xxx_messageInfo_CloneRepositoriesRequest.Size(m)
}
func (m *CloneRepositoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneRepositoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloneRepositoriesRequest proto.InternalMessageInfo

func (m *CloneRepositoriesRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CloneRepositoriesRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CloneRepositoriesRequest) GetSaveDir() string {
	if m != nil {
		return m.SaveDir
	}
	return ""
}

func (m *CloneRepositoriesRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CloneRepositoriesRequest) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

type CloneRepositoriesResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloneRepositoriesResponse) Reset()         { *m = CloneRepositoriesResponse{} }
func (m *CloneRepositoriesResponse) String() string { return proto.CompactTextString(m) }
func (*CloneRepositoriesResponse) ProtoMessage()    {}
func (*CloneRepositoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gitcrow_7ef2d37406cf996b, []int{1}
}
func (m *CloneRepositoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneRepositoriesResponse.Unmarshal(m, b)
}
func (m *CloneRepositoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneRepositoriesResponse.Marshal(b, m, deterministic)
}
func (dst *CloneRepositoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneRepositoriesResponse.Merge(dst, src)
}
func (m *CloneRepositoriesResponse) XXX_Size() int {
	return xxx_messageInfo_CloneRepositoriesResponse.Size(m)
}
func (m *CloneRepositoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneRepositoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloneRepositoriesResponse proto.InternalMessageInfo

func (m *CloneRepositoriesResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CloneRepositoriesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DownloadRepositoriesRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	SaveDir              string   `protobuf:"bytes,3,opt,name=save_dir,json=saveDir,proto3" json:"save_dir,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo                 string   `protobuf:"bytes,5,opt,name=repo,proto3" json:"repo,omitempty"`
	Tag                  string   `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadRepositoriesRequest) Reset()         { *m = DownloadRepositoriesRequest{} }
func (m *DownloadRepositoriesRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRepositoriesRequest) ProtoMessage()    {}
func (*DownloadRepositoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gitcrow_7ef2d37406cf996b, []int{2}
}
func (m *DownloadRepositoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRepositoriesRequest.Unmarshal(m, b)
}
func (m *DownloadRepositoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRepositoriesRequest.Marshal(b, m, deterministic)
}
func (dst *DownloadRepositoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRepositoriesRequest.Merge(dst, src)
}
func (m *DownloadRepositoriesRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadRepositoriesRequest.Size(m)
}
func (m *DownloadRepositoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRepositoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRepositoriesRequest proto.InternalMessageInfo

func (m *DownloadRepositoriesRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DownloadRepositoriesRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *DownloadRepositoriesRequest) GetSaveDir() string {
	if m != nil {
		return m.SaveDir
	}
	return ""
}

func (m *DownloadRepositoriesRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DownloadRepositoriesRequest) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *DownloadRepositoriesRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type DownloadRepositoriesResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadRepositoriesResponse) Reset()         { *m = DownloadRepositoriesResponse{} }
func (m *DownloadRepositoriesResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadRepositoriesResponse) ProtoMessage()    {}
func (*DownloadRepositoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gitcrow_7ef2d37406cf996b, []int{3}
}
func (m *DownloadRepositoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRepositoriesResponse.Unmarshal(m, b)
}
func (m *DownloadRepositoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRepositoriesResponse.Marshal(b, m, deterministic)
}
func (dst *DownloadRepositoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRepositoriesResponse.Merge(dst, src)
}
func (m *DownloadRepositoriesResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadRepositoriesResponse.Size(m)
}
func (m *DownloadRepositoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRepositoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRepositoriesResponse proto.InternalMessageInfo

func (m *DownloadRepositoriesResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DownloadRepositoriesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CloneRepositoriesRequest)(nil), "taxio.gitcrow.CloneRepositoriesRequest")
	proto.RegisterType((*CloneRepositoriesResponse)(nil), "taxio.gitcrow.CloneRepositoriesResponse")
	proto.RegisterType((*DownloadRepositoriesRequest)(nil), "taxio.gitcrow.DownloadRepositoriesRequest")
	proto.RegisterType((*DownloadRepositoriesResponse)(nil), "taxio.gitcrow.DownloadRepositoriesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GitcrowServiceClient is the client API for GitcrowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GitcrowServiceClient interface {
	CloneRepositories(ctx context.Context, in *CloneRepositoriesRequest, opts ...grpc.CallOption) (*CloneRepositoriesResponse, error)
	DownloadRepositories(ctx context.Context, in *DownloadRepositoriesRequest, opts ...grpc.CallOption) (*DownloadRepositoriesResponse, error)
}

type gitcrowServiceClient struct {
	cc *grpc.ClientConn
}

func NewGitcrowServiceClient(cc *grpc.ClientConn) GitcrowServiceClient {
	return &gitcrowServiceClient{cc}
}

func (c *gitcrowServiceClient) CloneRepositories(ctx context.Context, in *CloneRepositoriesRequest, opts ...grpc.CallOption) (*CloneRepositoriesResponse, error) {
	out := new(CloneRepositoriesResponse)
	err := c.cc.Invoke(ctx, "/taxio.gitcrow.GitcrowService/CloneRepositories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitcrowServiceClient) DownloadRepositories(ctx context.Context, in *DownloadRepositoriesRequest, opts ...grpc.CallOption) (*DownloadRepositoriesResponse, error) {
	out := new(DownloadRepositoriesResponse)
	err := c.cc.Invoke(ctx, "/taxio.gitcrow.GitcrowService/DownloadRepositories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitcrowServiceServer is the server API for GitcrowService service.
type GitcrowServiceServer interface {
	CloneRepositories(context.Context, *CloneRepositoriesRequest) (*CloneRepositoriesResponse, error)
	DownloadRepositories(context.Context, *DownloadRepositoriesRequest) (*DownloadRepositoriesResponse, error)
}

func RegisterGitcrowServiceServer(s *grpc.Server, srv GitcrowServiceServer) {
	s.RegisterService(&_GitcrowService_serviceDesc, srv)
}

func _GitcrowService_CloneRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitcrowServiceServer).CloneRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taxio.gitcrow.GitcrowService/CloneRepositories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitcrowServiceServer).CloneRepositories(ctx, req.(*CloneRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitcrowService_DownloadRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitcrowServiceServer).DownloadRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taxio.gitcrow.GitcrowService/DownloadRepositories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitcrowServiceServer).DownloadRepositories(ctx, req.(*DownloadRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GitcrowService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "taxio.gitcrow.GitcrowService",
	HandlerType: (*GitcrowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CloneRepositories",
			Handler:    _GitcrowService_CloneRepositories_Handler,
		},
		{
			MethodName: "DownloadRepositories",
			Handler:    _GitcrowService_DownloadRepositories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gitcrow.proto",
}

func init() { proto.RegisterFile("gitcrow.proto", fileDescriptor_gitcrow_7ef2d37406cf996b) }

var fileDescriptor_gitcrow_7ef2d37406cf996b = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0xcd, 0xea, 0xd3, 0x40,
	0x10, 0x27, 0xfd, 0xee, 0xd6, 0x16, 0xbb, 0xf4, 0xb0, 0x4d, 0x7b, 0xd0, 0x88, 0x58, 0x2a, 0x24,
	0xa0, 0xb7, 0x7a, 0xd3, 0x82, 0x08, 0x9e, 0xa2, 0x27, 0x2f, 0x65, 0x93, 0x8c, 0x71, 0xb1, 0xd9,
	0x59, 0x77, 0x37, 0xad, 0xbd, 0x0a, 0x3e, 0x41, 0xef, 0xbe, 0x84, 0x8f, 0xe2, 0x2b, 0xf8, 0x20,
	0x92, 0x4d, 0x14, 0xd4, 0xfa, 0xc1, 0xff, 0xf4, 0xbf, 0xcd, 0xef, 0x23, 0xc3, 0x6f, 0x27, 0x33,
	0x64, 0x9c, 0x0b, 0x9b, 0x6a, 0x3c, 0x86, 0x4a, 0xa3, 0x45, 0x3a, 0xb6, 0xfc, 0xbd, 0xc0, 0xb0,
	0x21, 0xfd, 0x65, 0x8e, 0x98, 0xef, 0x21, 0xe2, 0x4a, 0x44, 0x5c, 0x4a, 0xb4, 0xdc, 0x0a, 0x94,
	0xa6, 0x36, 0xfb, 0x8b, 0x46, 0x75, 0x28, 0x29, 0x5f, 0x47, 0x50, 0x28, 0x7b, 0xaa, 0xc5, 0xe0,
	0x93, 0x47, 0xd8, 0x93, 0x3d, 0x4a, 0x88, 0x41, 0xa1, 0x11, 0x16, 0xb5, 0x00, 0x13, 0xc3, 0xbb,
	0x12, 0x8c, 0xa5, 0x3e, 0x19, 0x94, 0x06, 0xb4, 0xe4, 0x05, 0x30, 0xef, 0x96, 0xb7, 0x1a, 0xc6,
	0x3f, 0x30, 0xbd, 0x4d, 0x6e, 0xf0, 0x34, 0x05, 0x63, 0x76, 0x16, 0xdf, 0x82, 0x64, 0x2d, 0xa7,
	0x8f, 0x6a, 0xee, 0x65, 0x45, 0xd1, 0x39, 0x19, 0x18, 0x7e, 0x80, 0x5d, 0x26, 0x34, 0x6b, 0x3b,
	0xb9, 0x5f, 0xe1, 0xad, 0xd0, 0x74, 0x46, 0xba, 0x78, 0x94, 0xa0, 0x59, 0xc7, 0xf1, 0x35, 0xa0,
	0x94, 0x74, 0x34, 0x28, 0x64, 0x5d, 0x47, 0xba, 0x3a, 0x78, 0x46, 0xe6, 0x17, 0xf2, 0x19, 0x85,
	0xd2, 0x40, 0xf5, 0x41, 0x8a, 0x59, 0x1d, 0xae, 0x1b, 0xbb, 0x9a, 0x32, 0xd2, 0x2f, 0xc0, 0x18,
	0x9e, 0x43, 0x93, 0xe9, 0x3b, 0x0c, 0x3e, 0x7b, 0x64, 0xb1, 0xc5, 0xa3, 0xdc, 0x23, 0xcf, 0xae,
	0xe9, 0x73, 0xe9, 0x4d, 0xd2, 0xb6, 0x3c, 0x67, 0x3d, 0x47, 0x55, 0x65, 0xf0, 0x9c, 0x2c, 0x2f,
	0x87, 0xbe, 0xca, 0x0c, 0x1e, 0x9c, 0x5b, 0x64, 0xf2, 0xb4, 0x5e, 0x9b, 0x17, 0xa0, 0x0f, 0x22,
	0x05, 0x7a, 0x22, 0xd3, 0xdf, 0x26, 0x4c, 0xef, 0x85, 0x3f, 0xad, 0x58, 0xf8, 0xa7, 0x1d, 0xf1,
	0x57, 0xff, 0x36, 0xd6, 0x41, 0x83, 0xe9, 0x87, 0x2f, 0x5f, 0xcf, 0xad, 0x51, 0xd0, 0x8b, 0xd2,
	0xca, 0xb3, 0xf1, 0xd6, 0xf4, 0xa3, 0x47, 0x66, 0x97, 0x1e, 0x47, 0xd7, 0xbf, 0x74, 0xfd, 0xcb,
	0x6f, 0xf3, 0xef, 0xff, 0x97, 0xb7, 0x09, 0x31, 0x73, 0x21, 0x26, 0xc1, 0x30, 0xca, 0x1a, 0xdb,
	0xc6, 0x5b, 0x3f, 0xbe, 0xfb, 0xea, 0x4e, 0x2e, 0xec, 0x9b, 0x32, 0x09, 0x53, 0x2c, 0x22, 0xd7,
	0x2e, 0x6a, 0xda, 0x55, 0x47, 0xf5, 0x88, 0x2b, 0xb1, 0x53, 0x49, 0xd2, 0x73, 0x37, 0xf3, 0xf0,
	0x5b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xac, 0x2b, 0xff, 0x8e, 0x03, 0x00, 0x00,
}
